import { TCGEvent } from './types';

export const ALL_EVENTS: TCGEvent[] = [
  // ─── POKÉMON TCG ──────────────────────────────────────────────────────────
  {
    id: 'pkm-ascended-heroes',
    game: 'pokemon',
    date: '2026-01-30',
    title: 'Ascesa Eroica',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Set Megaevoluzione — primo set del 2026. Nuovo sottotipo Mega ex, meccanica di evoluzione rinnovata.',
    sourceUrl: 'https://tcg.pokemon.com/en-us/expansions/ascended-heroes/',
  },
  {
    id: 'pkm-pokemon-day',
    game: 'pokemon',
    date: '2026-02-27',
    title: 'Pokémon Day — 30° Anniversario',
    type: 'popculture',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      '30° anniversario del franchise. Anchor annuale — avvia una campagna fedeltà "Road to 30" che culmina nel lancio mondiale di settembre.',
    isMajor: true,
    sourceUrl: 'https://www.pokemon.com/us/pokemon-news/',
  },
  {
    id: 'pkm-perfect-order',
    game: 'pokemon',
    date: '2026-03-27',
    title: 'Equilibrio Perfetto',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Set Megaevoluzione — tie-in con Legends: Z-A. Primo set a includere il nuovo formato di Showcase.',
    sourceUrl: 'https://tcg.pokemon.com/en-us/expansions/perfect-order/',
  },
  {
    id: 'pkm-chaos-rising-pre',
    game: 'pokemon',
    date: '2026-05-09',
    endDate: '2026-05-17',
    title: 'Prerelease Caos Nascente',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description: 'Weekend prerelease per Caos Nascente (Mega Greninja ex). Kit da 6 buste + promo esclusiva.',
    sourceUrl: 'https://tcg.pokemon.com/en-us/expansions/chaos-rising/',
  },
  {
    id: 'pkm-chaos-rising',
    game: 'pokemon',
    date: '2026-05-22',
    title: 'Caos Nascente',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Set Megaevoluzione con Mega Greninja ex come carta di punta. Forti meccaniche Water/Darkness.',
    sourceUrl: 'https://tcg.pokemon.com/en-us/expansions/chaos-rising/',
  },
  {
    id: 'pkm-first-partner',
    game: 'pokemon',
    date: '2026-06-19',
    title: 'First Partner Illustration Collection S2',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description:
      'Serie 2 — Illustrazioni dei partner iniziali di Johto, Unova e Galar. Cofanetto premium da collezionismo.',
    addedInBatch: '2026-05-15',
    sourceUrl: 'https://www.pokemon.com/us/pokemon-tcg/product-gallery/first-partner-illustration-collection-series-2/',
  },
  {
    id: 'pkm-pitch-black-pre',
    game: 'pokemon',
    date: '2026-07-04',
    endDate: '2026-07-12',
    title: 'Prerelease Buio Pesto',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description: 'Weekend prerelease per Buio Pesto (Mega Darkrai ex). Kit da 6 buste + promo esclusiva.',
    addedInBatch: '2026-05-01',
    sourceUrl: 'https://www.serebii.net/card/pitchblack/',
  },
  {
    id: 'pkm-pitch-black',
    game: 'pokemon',
    date: '2026-07-17',
    title: 'Buio Pesto',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Set Megaevoluzione con Mega Darkrai ex. Alta domanda tra i collezionisti per le illustrazioni notturne.',
    addedInBatch: '2026-05-01',
    sourceUrl: 'https://www.serebii.net/card/pitchblack/',
  },
  {
    id: 'pkm-storm-emerald',
    game: 'pokemon',
    date: '2026-09-04',
    title: 'Tempesta Smeraldo ⚠',
    type: 'release',
    priority: 'important',
    confidence: 'rumored',
    description:
      'Set Megaevoluzione con Mega Rayquaza ex. Finestra agosto/settembre — verifica la data prima di promuovere.',
    sourceUrl: 'https://www.pokebeach.com/2026/02/abyss-eye-set-and-storm-emeralda-set-preliminary-details-revealed/',
  },
  {
    id: 'pkm-30th-celebration',
    game: 'pokemon',
    date: '2026-09-18',
    title: '★ 30° Anniversario — Lancio Mondiale',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Primo lancio mondiale simultaneo. Buste da 6 carte tutte-foil, nuova rarità, ristampe classiche. Deck Set Premium: Espeon & Umbreon stesso giorno. (JP 16 set) — massima domanda sealed dell\'anno.',
    isMajor: true,
    sourceUrl: 'https://tcg.pokemon.com/en-us/expansions/30th-celebration/',
  },
  {
    id: 'pkm-30th-card-sets',
    game: 'pokemon',
    date: '2026-10-16',
    title: 'Nove Set Carte 30° Anniversario ⚠',
    type: 'release',
    priority: 'opportunity',
    confidence: 'rumored',
    description:
      'Promo Pokémon iniziali per tutte e 9 le generazioni. Verifica la data prima della campagna.',
    sourceUrl: 'https://www.pokemon.com/us/pokemon-news/',
  },

  // ─── ONE PIECE CARD GAME ──────────────────────────────────────────────────
  {
    id: 'op14',
    game: 'one-piece',
    date: '2026-01-16',
    title: 'OP-14 "The Azure Sea\'s Seven" + ST-29 Egghead',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Booster I Sette Viceré + Double Pack DP-09 + ST-29 Egghead starter deck. Forte apertura d\'anno; starter deck = rampa di ingresso per nuovi giocatori.',
    isMajor: true,
    sourceUrl: 'https://en.onepiece-cardgame.com/products/boosters/op14-eb04.php',
  },
  {
    id: 'op-eb03',
    game: 'one-piece',
    date: '2026-02-15',
    title: 'EB-03 Heroines Edition + Set 3° Anniversario',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Extra booster + set premium 3° anniversario (Tre Fratelli, Premium Bandai). Release inglese.',
    sourceUrl: 'https://en.onepiece-cardgame.com/products/boosters/eb03.php',
  },
  {
    id: 'op-treasure-cup-mar',
    game: 'one-piece',
    date: '2026-03-15',
    title: 'Treasure Cup — Marzo',
    type: 'competitive',
    priority: 'important',
    confidence: 'expected',
    description: 'Evento competitivo Treasure Cup, stagione marzo.',
    sourceUrl: 'https://en.onepiece-cardgame.com/events/2026/treasure_cup_march/',
  },
  {
    id: 'op15',
    game: 'one-piece',
    date: '2026-04-03',
    title: 'OP-15 "Adventure on Kami\'s Island"',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Arco Skypiea — Luffy vs Enel. Primo lancio global-sync da OP-15 in poi.',
    sourceUrl: 'https://en.onepiece-cardgame.com/products/boosters/op15-eb04.php',
  },
  {
    id: 'op-store-champ-s1',
    game: 'one-piece',
    date: '2026-04-18',
    title: 'Store Championship 2026 Vol.1',
    type: 'competitive',
    priority: 'important',
    confidence: 'expected',
    description: 'One Piece Store Championship Stagione 1 — aprile.',
    addedInBatch: '2026-05-15',
    sourceUrl: 'https://en.onepiece-cardgame.com/events/2026/championship/store_championship_april.php',
  },
  {
    id: 'op-treasure-cup-may',
    game: 'one-piece',
    date: '2026-05-16',
    title: 'Treasure Cup — Maggio',
    type: 'competitive',
    priority: 'important',
    confidence: 'expected',
    description: 'Evento competitivo Treasure Cup, stagione maggio.',
    sourceUrl: 'https://en.onepiece-cardgame.com/events/2026/treasure-cup-may/',
  },
  {
    id: 'op16',
    game: 'one-piece',
    date: '2026-06-12',
    title: 'OP-16 "The Time of Battle"',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Arco Marineford — tripla Manga Rare. Massimo hype: crossover competitivo + collezionisti. Data confermata.',
    isMajor: true,
    addedInBatch: '2026-06-08',
    sourceUrl: 'https://en.onepiece-cardgame.com/products/op16.html',
  },

  // ─── DISNEY LORCANA ───────────────────────────────────────────────────────
  {
    id: 'lrc-winterspell',
    game: 'lorcana',
    date: '2026-02-20',
    title: 'Winterspell',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Set a tema invernale con Paperon de\' Paperoni e personaggi di Frozen. 11° set Lorcana.',
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/winterspell',
  },
  {
    id: 'lrc-scrooge-gift',
    game: 'lorcana',
    date: '2026-03-13',
    title: 'Scrooge McDuck Gift Box',
    type: 'accessory',
    priority: 'optional',
    confidence: 'confirmed',
    description: 'Cofanetto regalo Paperon de\' Paperoni — prodotto da collezionismo.',
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/winterspell',
  },
  {
    id: 'lrc-wilds-pre',
    game: 'lorcana',
    date: '2026-05-08',
    title: 'Prerelease Wilds Unknown',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description: 'Weekend prerelease per Wilds Unknown — primo set Pixar.',
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/wilds-unknown',
  },
  {
    id: 'lrc-wilds-unknown',
    game: 'lorcana',
    date: '2026-05-15',
    title: '★ Wilds Unknown — Primo Set Pixar',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Primo set Pixar: Toy Story, Gli Incredibili, Ribelle + Starter Set 2 giocatori. Apre al pubblico famiglie/casual. Organizza un pomeriggio genitori+figli in store.',
    isMajor: true,
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/wilds-unknown',
  },
  {
    id: 'lrc-attack-vine-pre',
    game: 'lorcana',
    date: '2026-07-17',
    title: 'Prerelease Attack of the Vine!',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description: 'Weekend prerelease per Attack of the Vine! (Monsters & Co.)',
    addedInBatch: '2026-06-01',
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/attack-of-the-vine',
  },
  {
    id: 'lrc-attack-vine',
    game: 'lorcana',
    date: '2026-07-24',
    title: 'Attack of the Vine! + Core Rotation',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Set Monsters & Co. + rotazione Core Constructed. La rotazione guida nuovi acquisti e ricambio di singole.',
    isMajor: true,
    addedInBatch: '2026-06-01',
    sourceUrl: 'https://www.disneylorcana.com/en-US/product/attack-of-the-vine',
  },
  {
    id: 'lrc-hunny-rescue',
    game: 'lorcana',
    date: '2026-10-01',
    title: "Illumineer's Quest: The Great Hunny Rescue",
    type: 'release',
    priority: 'opportunity',
    confidence: 'expected',
    description: 'Box cooperativo ($59.99). Finestra ottobre.',
    sourceUrl: 'https://www.disneylorcana.com/en-US/',
  },
  {
    id: 'lrc-q4-set',
    game: 'lorcana',
    date: '2026-11-15',
    title: 'Set Q4 Unnamed ⚠',
    type: 'release',
    priority: 'important',
    confidence: 'rumored',
    description:
      'Hyperia City — Coco (Miguel) + 2° Starter Set 2 giocatori. Verifica la data prima di promuovere.',
    sourceUrl: 'https://www.disneylorcana.com/en-US/',
  },

  // ─── MAGIC: THE GATHERING ─────────────────────────────────────────────────
  {
    id: 'mtg-tmnt',
    game: 'magic',
    date: '2026-02-10',
    title: 'Teenage Mutant Ninja Turtles (UB)',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description:
      'Universes Beyond — TMNT + box Turtle Team-Up. Forte crossover pop-culture.',
    sourceUrl: 'https://magic.wizards.com/en/products/teenage-mutant-ninja-turtles',
  },
  {
    id: 'mtg-strixhaven',
    game: 'magic',
    date: '2026-04-15',
    title: 'Secrets of Strixhaven ⚠',
    type: 'release',
    priority: 'important',
    confidence: 'rumored',
    description:
      'Set originale Strixhaven. Data instabile — verifica su Scryfall /sets prima di comunicare.',
    sourceUrl: 'https://scryfall.com/sets',
  },
  {
    id: 'mtg-marvel',
    game: 'magic',
    date: '2026-06-26',
    title: '★ Marvel Super Heroes (UB)',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Universes Beyond — Scarlet Witch, Doctor Doom e altri. Rete pop-culture più ampia dell\'anno; raggiunge fan Marvel non-Magic. Data confermata.',
    isMajor: true,
    addedInBatch: '2026-06-08',
    sourceUrl: 'https://magic.wizards.com/en/products/marvel/marvel-super-heroes',
  },
  {
    id: 'mtg-hobbit',
    game: 'magic',
    date: '2026-08-15',
    title: 'The Hobbit (UB) ⚠',
    type: 'release',
    priority: 'important',
    confidence: 'rumored',
    description:
      'Universes Beyond — Lo Hobbit. Finestra agosto approssimativa; verifica data.',
    sourceUrl: 'https://scryfall.com/sets',
  },
  {
    id: 'mtg-reality-fracture',
    game: 'magic',
    date: '2026-09-10',
    title: 'Reality Fracture ⚠',
    type: 'release',
    priority: 'important',
    confidence: 'rumored',
    description:
      'Set originale che conclude l\'arco narrativo attuale + mazzi Commander Foundations.',
    sourceUrl: 'https://scryfall.com/sets',
  },
  {
    id: 'mtg-star-trek',
    game: 'magic',
    date: '2026-11-13',
    title: 'Star Trek (UB)',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description:
      'Universes Beyond — Star Trek. Forte pubblico Trekkie/fantascienza.',
    sourceUrl: 'https://magic.wizards.com/en/products/star-trek',
  },

  // ─── YU-GI-OH! ────────────────────────────────────────────────────────────
  {
    id: 'ygo-spirit-charmers',
    game: 'yugioh',
    date: '2026-01-23',
    title: 'The Chronicles Deck: Spirit Charmers',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description:
      'Chronicles Deck Spirit Charmers — edizione all-foil del mazzo struttura classico.',
    sourceUrl: 'https://yugipedia.com/wiki/THE_CHRONICLES_DECK:_Spirit_Charmers_(All-Foil_Edition)',
  },
  {
    id: 'ygo-burst-protocol',
    game: 'yugioh',
    date: '2026-01-30',
    title: 'Burst Protocol',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Booster principale con supporto agli archetipi Rokket e Signore delle Tenebre.',
    sourceUrl: 'https://yugipedia.com/wiki/Burst_Protocol',
  },
  {
    id: 'ygo-maze-muertos',
    game: 'yugioh',
    date: '2026-02-20',
    title: 'Maze of Muertos',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Set booster — supporto Zombie e Mago Oscuro.',
    sourceUrl: 'https://yugipedia.com/wiki/Maze_of_Muertos',
  },
  {
    id: 'ygo-legendary-decks',
    game: 'yugioh',
    date: '2026-03-13',
    title: 'Legendary Modern Decks 2026',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description: 'Set mazzi Sky Strikers, X-Sabers e Mitsurugi.',
    sourceUrl: 'https://yugipedia.com/wiki/Legendary_Modern_Decks_2026',
  },
  {
    id: 'ygo-rarity-5',
    game: 'yugioh',
    date: '2026-04-10',
    title: '★ Rarity Collection 5',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Alta densità di chase. Sell-through sealed + contenuto stream di apertura box. Vendite solide garantite.',
    isMajor: true,
    sourceUrl: 'https://yugipedia.com/wiki/Rarity_Collection_5',
  },
  {
    id: 'ygo-blazing-dominion',
    game: 'yugioh',
    date: '2026-05-08',
    title: 'Blazing Dominion',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Booster principale con supporto Jack Atlas e Drago Oscuro Rosso. 4° e ultimo booster della Serie 13.',
    sourceUrl: 'https://yugipedia.com/wiki/Blazing_Dominion',
  },
  {
    id: 'ygo-battles-legend',
    game: 'yugioh',
    date: '2026-06-05',
    title: 'Battles of Legend: Glorious Gallery',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Booster annuale Battles of Legend con ristampe rare e nuove carte. 5 carte per busta (1 Secret + 4 Ultra).',
    addedInBatch: '2026-06-08',
    sourceUrl: 'https://yugipedia.com/wiki/Battles_of_Legend:_Glorious_Gallery',
  },
  {
    id: 'ygo-ultimate-pack',
    game: 'yugioh',
    date: '2026-06-17',
    title: 'Ultimate Tournament Pack 1',
    type: 'release',
    priority: 'opportunity',
    confidence: 'confirmed',
    description: 'Prodotto organized play — Ultimate Tournament Pack 1. Premio torneo OTS.',
    addedInBatch: '2026-06-08',
    sourceUrl: 'https://yugipedia.com/wiki/Ultimate_Tournament_Pack_1',
  },

  // ─── RIFTBOUND ────────────────────────────────────────────────────────────
  {
    id: 'rft-spiritforged-pre',
    game: 'riftbound',
    date: '2026-02-06',
    endDate: '2026-02-12',
    title: 'Prerelease Spiritforged',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Prerelease Spiritforged. Release inglese con 221 carte, 12 campioni.',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/news/announcements/after-origins-spiritforged-slices-into-riftbound/',
  },
  {
    id: 'rft-spiritforged',
    game: 'riftbound',
    date: '2026-02-13',
    title: 'Spiritforged',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description:
      'Lancio inglese — 221 carte, 12 campioni. Opportunità crossover con il pubblico LoL/esports.',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/news/announcements/after-origins-spiritforged-slices-into-riftbound/',
  },
  {
    id: 'rft-unleashed-pre',
    game: 'riftbound',
    date: '2026-05-01',
    endDate: '2026-05-07',
    title: 'Prerelease Unleashed',
    type: 'prerelease',
    priority: 'must_do',
    confidence: 'confirmed',
    description: 'Prerelease per il set Unleashed.',
    addedInBatch: '2026-05-01',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/news/announcements/the-unleashed-overview/',
  },
  {
    id: 'rft-unleashed',
    game: 'riftbound',
    date: '2026-05-08',
    title: 'Unleashed',
    type: 'release',
    priority: 'important',
    confidence: 'confirmed',
    description: 'Release inglese — Vi, LeBlanc, Rengar, Poppy. Nuova meccanica XP.',
    addedInBatch: '2026-05-01',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/news/announcements/the-unleashed-overview/',
  },
  {
    id: 'rft-vendetta',
    game: 'riftbound',
    date: '2026-07-31',
    title: '★ Vendetta — Primo Lancio Globale Simultaneo',
    type: 'release',
    priority: 'must_do',
    confidence: 'confirmed',
    description:
      'Prima release globale simultanea — Ambessa, Mel, Akali + Showdown Deck (Zed vs Shen). Pubblico LoL/esports. Co-organizza con un bar esports o gaming café locale.',
    isMajor: true,
    addedInBatch: '2026-06-01',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/news/announcements/riftbounds-latest-2026-roadmap/',
  },
  {
    id: 'rft-radiance',
    game: 'riftbound',
    date: '2026-10-23',
    title: 'Radiance',
    type: 'release',
    priority: 'important',
    confidence: 'expected',
    description: 'Quarto set Riftbound.',
    sourceUrl: 'https://riftbound.leagueoflegends.com/en-us/',
  },
];

// ─── SERATE STORIE ────────────────────────────────────────────────────────────
// Appuntamento settimanale ogni lunedì a partire dal 15 giugno 2026.
// Per aggiungere una nuova serata, copia uno dei blocchi qui sotto e cambia
// id, date e title. Il campo `game` indica il gioco principale della serata.
//
// Esempio:
// { id: 'gn-2026-07-06', game: 'pokemon', date: '2026-07-06', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed' },
//
export const GAME_NIGHTS: TCGEvent[] = [
  // Giugno
  { id: 'gn-2026-06-15', game: 'pokemon',   date: '2026-06-15', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-06-22', game: 'one-piece', date: '2026-06-22', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-06-29', game: 'magic',     date: '2026-06-29', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Luglio
  { id: 'gn-2026-07-06', game: 'yugioh',    date: '2026-07-06', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-07-13', game: 'pokemon',   date: '2026-07-13', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-07-20', game: 'one-piece', date: '2026-07-20', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-07-27', game: 'magic',     date: '2026-07-27', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Agosto
  { id: 'gn-2026-08-03', game: 'yugioh',    date: '2026-08-03', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-08-10', game: 'pokemon',   date: '2026-08-10', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-08-17', game: 'one-piece', date: '2026-08-17', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-08-24', game: 'magic',     date: '2026-08-24', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-08-31', game: 'yugioh',    date: '2026-08-31', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Settembre
  { id: 'gn-2026-09-07', game: 'pokemon',   date: '2026-09-07', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-09-14', game: 'one-piece', date: '2026-09-14', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-09-21', game: 'magic',     date: '2026-09-21', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-09-28', game: 'yugioh',    date: '2026-09-28', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Ottobre
  { id: 'gn-2026-10-05', game: 'pokemon',   date: '2026-10-05', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-10-12', game: 'one-piece', date: '2026-10-12', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-10-19', game: 'magic',     date: '2026-10-19', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-10-26', game: 'yugioh',    date: '2026-10-26', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Novembre
  { id: 'gn-2026-11-02', game: 'pokemon',   date: '2026-11-02', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-11-09', game: 'one-piece', date: '2026-11-09', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-11-16', game: 'magic',     date: '2026-11-16', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-11-23', game: 'yugioh',    date: '2026-11-23', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-11-30', game: 'pokemon',   date: '2026-11-30', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  // Dicembre
  { id: 'gn-2026-12-07', game: 'one-piece', date: '2026-12-07', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-12-14', game: 'magic',     date: '2026-12-14', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-12-21', game: 'yugioh',    date: '2026-12-21', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
  { id: 'gn-2026-12-28', game: 'pokemon',   date: '2026-12-28', title: 'Serata Stories — Lunedì', type: 'game_night', priority: 'optional', confidence: 'confirmed', description: 'Serata eventi in store — crea Stories dal vivo: arrivo dei giocatori, partite, vincitore della serata.' },
];
